apiVersion: v1
kind: Service
metadata:
  name: advanced-calculator-api-service
spec:
  selector:
    app: advanced-calculator-api  # Label selector to target the pods
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 1515  # Port on application listens 
  type: NodePort  # Service type (NodePort, ClusterIP, LoadBalancer)
