apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc-new-2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-hostpath-storage  # Reference the StorageClass here
  resources:
    requests:
      storage: 1Gi